### ISSUE TITLE
Timezone?

### ISSUE THREAD

**Issue by hypnagogicangel** [MissingNo96/Dob-to-age#1]
You have a `timezone` perameter in the main function but I dont see any code using that perameter.
I wanted a function which would tell the date of birth according to my preferred timezone ( IST ), so are you going to add something like that using the perameter?

**Comment by MissingNo96** [comment]
Hey! I'm sorry for that as I was planning on adding a way to find date of birth according to different timezones, but I don't really know how to do that and also I'm not getting time for code and stuff. Sorry for inconvenience I'll remove that code which I'm not planning to develop further any time soon. Thanks for letting me know that people are using my code :)
